[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/gocolly/colly"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/alexeyco/simpletable"
