version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  build:
    environment:
      - GOPATH: /home/circleci/go
    docker:
      - image: circleci/golang:1.14
    working_directory: /home/circleci/go/src/github.com/k-kurikuri/sort-awesome-go-by-stars
    steps:
      - run: echo 'export PATH=${GOPATH}/bin/:${PATH}' >> $BASH_ENV
      - checkout
      - run: go test -v -race ./... -coverprofile=coverage.txt -covermode=atomic
      - run: bash <(curl -s https://codecov.io/bash)
workflows:
  build:
    jobs:
      - build
